title: Михаил Минюков DevOps Engineer
markdown: kramdown
url: ""
baseurl: ""
google_analytics: G-XQB10Q8MX9

# for atom feed
author:
  name: Михаил Минюков
  email: minyukov1606@gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
